// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: EbikeDemo

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Driving
void ui_Driving_screen_init(void);
lv_obj_t *ui_Driving;
lv_obj_t *ui_BG1;
lv_obj_t *ui_GroupClock;
lv_obj_t *ui_NumberMinute;
lv_obj_t *ui_NumberHour;
lv_obj_t *ui_NumberColon;
lv_obj_t *ui_SliderHour;
lv_obj_t *ui_SliderMin;
lv_obj_t *ui_GroupHeader;
lv_obj_t *ui_HeadImage;
lv_obj_t *ui_HeadLabel;
lv_obj_t *ui_HeadWifiOn;
lv_obj_t *ui_HeadWifiOff;
lv_obj_t *ui_GroupMinute;
lv_obj_t *ui_Label_Number1;
lv_obj_t *ui_Label_Number2;
lv_obj_t *ui_Label_Number3;
lv_obj_t *ui_Label_Number4;
lv_obj_t *ui_Label_Number5;
lv_obj_t *ui_GroupHour;
lv_obj_t *ui_Label_Number6;
lv_obj_t *ui_Label_Number8;
lv_obj_t *ui_Label_Number10;
lv_obj_t *ui_GroupDate;
lv_obj_t *ui_LabelWeek;
lv_obj_t *ui_LabelDate;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_basic_init(dispp);
    lv_disp_set_theme(dispp, theme);
    ui_Driving_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Driving);
}
