// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: EbikeDemo

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
lv_obj_t *ui_HomeScreen;
lv_obj_t *ui_BG1;
lv_obj_t *ui_GroupClock;
lv_obj_t *ui_NumberMinute;
lv_obj_t *ui_NumberHour;
lv_obj_t *ui_NumberColon;
lv_obj_t *ui_SliderHour;
lv_obj_t *ui_SliderMin;
lv_obj_t *ui_GroupHeader;
lv_obj_t *ui_HeadImage;
lv_obj_t *ui_HeadLabel;
lv_obj_t *ui_HeadWifiOn;
lv_obj_t *ui_HeadWifiOff;
lv_obj_t *ui_GroupMinute;
lv_obj_t *ui_Label_Number1;
lv_obj_t *ui_Label_Number2;
lv_obj_t *ui_Label_Number3;
lv_obj_t *ui_Label_Number4;
lv_obj_t *ui_Label_Number5;
lv_obj_t *ui_GroupHour;
lv_obj_t *ui_Label_Number6;
lv_obj_t *ui_Label_Number8;
lv_obj_t *ui_Label_Number10;
lv_obj_t *ui_GroupDate;
lv_obj_t *ui_LabelWeek;
lv_obj_t *ui_LabelDate;
lv_obj_t *ui_BottomGroup;
lv_obj_t *ui_BottomBg;
void ui_event_BottomTimerImage( lv_event_t * e);
lv_obj_t *ui_BottomTimerImage;
lv_obj_t *ui_BgSlider;


// SCREEN: ui_TimerScreen
void ui_TimerScreen_screen_init(void);
lv_obj_t *ui_TimerScreen;
lv_obj_t *ui_GroupHeader1;
lv_obj_t *ui_HeadImage1;
lv_obj_t *ui_HeadLabel1;
lv_obj_t *ui_HeadWifiOn1;
lv_obj_t *ui_HeadWifiOff1;
lv_obj_t *ui_TImeHour;
lv_obj_t *ui_TImeColon1;
lv_obj_t *ui_TImeMinute;
lv_obj_t *ui_TImeColon2;
lv_obj_t *ui_TImeSecond;
void ui_event_TimerStartBtn( lv_event_t * e);
lv_obj_t *ui_TimerStartBtn;
lv_obj_t *ui_StartBtnImage;
lv_obj_t *ui_StartBtnLabel;
void ui_event_TimerStopBtn( lv_event_t * e);
lv_obj_t *ui_TimerStopBtn;
lv_obj_t *ui_StopBtnImage;
lv_obj_t *ui_StopBtnLabel;
void ui_event_TimerExitImg( lv_event_t * e);
lv_obj_t *ui_TimerExitImg;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_548856303[1] = {&ui_img_400942075};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_BottomTimerImage( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_TimerScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_TimerScreen_screen_init);
}
}
void ui_event_TimerStartBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      TimerStartHandle( e );
      _ui_flag_modify( ui_TimerStartBtn, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_TimerStopBtn, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}
void ui_event_TimerStopBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      TimerStopHandle( e );
      _ui_flag_modify( ui_TimerStopBtn, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_TimerStartBtn, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}
void ui_event_TimerExitImg( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_HomeScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_HomeScreen_screen_init);
      TimerResetHandle( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_basic_init(dispp);
lv_disp_set_theme(dispp, theme);
ui_HomeScreen_screen_init();
ui_TimerScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_HomeScreen);
}
