// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: EbikeDemo

#ifndef _EBIKEDEMO_UI_H
#define _EBIKEDEMO_UI_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
    // SCREEN: ui_Driving
    void ui_Driving_screen_init(void);
    extern lv_obj_t *ui_Driving;
    extern lv_obj_t *ui_BG1;
    extern lv_obj_t *ui_GroupClock;
    extern lv_obj_t *ui_NumberMinute;
    extern lv_obj_t *ui_NumberHour;
    extern lv_obj_t *ui_NumberColon;
    extern lv_obj_t *ui_SliderHour;
    extern lv_obj_t *ui_SliderMin;
    extern lv_obj_t *ui_GroupHeader;
    extern lv_obj_t *ui_HeadImage;
    extern lv_obj_t *ui_HeadLabel;
    extern lv_obj_t *ui_HeadWifiOn;
    extern lv_obj_t *ui_HeadWifiOff;
    extern lv_obj_t *ui_GroupMinute;
    extern lv_obj_t *ui_Label_Number1;
    extern lv_obj_t *ui_Label_Number2;
    extern lv_obj_t *ui_Label_Number3;
    extern lv_obj_t *ui_Label_Number4;
    extern lv_obj_t *ui_Label_Number5;
    extern lv_obj_t *ui_GroupHour;
    extern lv_obj_t *ui_Label_Number6;
    extern lv_obj_t *ui_Label_Number8;
    extern lv_obj_t *ui_Label_Number10;
    extern lv_obj_t *ui_GroupDate;
    extern lv_obj_t *ui_LabelWeek;
    extern lv_obj_t *ui_LabelDate;
    extern lv_obj_t *ui____initial_actions0;

    LV_IMG_DECLARE(ui_img_ebike_bg_png);       // assets\ebike_bg.png
    LV_IMG_DECLARE(ui_img_speed_slider_png);   // assets\speed_slider.png
    LV_IMG_DECLARE(ui_img_slider_battery_png); // assets\slider_battery.png
    LV_IMG_DECLARE(ui_img_995809848);          // assets\kaola-fill.png
    LV_IMG_DECLARE(ui_img_652517623);          // assets\wifi-on.png
    LV_IMG_DECLARE(ui_img_1560645021);         // assets\wifi-off.png

    LV_FONT_DECLARE(ui_font_Big);
    LV_FONT_DECLARE(ui_font_Medium);
    LV_FONT_DECLARE(ui_font_Number);
    LV_FONT_DECLARE(ui_font_Small);

    void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
