// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: EbikeDemo

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C"
{
#endif

    extern bool isTimerRunning;
    extern bool isTimerReset;

    void TimerStartHandle(lv_event_t *e);
    void TimerStopHandle(lv_event_t *e);
    void TimerResetHandle(lv_event_t *e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
