// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: EbikeDemo

#include "ui.h"

bool isTimerRunning = false;
bool isTimerReset = false;

void TimerStartHandle(lv_event_t *e)
{
	// Your code here
	isTimerRunning = true;
}

void TimerStopHandle(lv_event_t *e)
{
	// Your code here
	isTimerRunning = false;
}

void TimerResetHandle(lv_event_t *e)
{
	// Your code here
	isTimerReset = true;
	_ui_flag_modify(ui_TimerStopBtn, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
	_ui_flag_modify(ui_TimerStartBtn, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
